### ISSUE TITLE
QM 5.2.5 refuses to load qpc.qm from qpc 7.3.0

### ISSUE THREAD

**Issue by stefanschober** [QuantumLeaps/qm#14]
The error message, which pops up, reads:
   ERROR F041> qpc.qm: failed to parse the model file

Is QM 5.2.5 incompatible with qpc 7.3's model file format?

Thanks, Stefan

**Comment by quantum-leaps** [comment]
Hi Stefan,
Thanks for your interest in the early (beta) version of QP/C.
Yes, the `qpc.qm` model was generated with the new (yet to be released) QM 5.3.0 and requires this version to be correctly opened and manipulated. The reason is the modified [class structure](https://www.state-machine.com/qpc/history.html#qpc_7_3_0) in QP/C/C++ 7.3.0, specifically the introduction of the [QAsm abstract base class (ABC)](https://www.state-machine.com/qpc/struct_q_asm.html). Also, the new QP/C source code uses the C++ style comments, which requires QM 5.3.0. (C++ style comments are part of the C99 standard and are no longer frowned upon by MISRA-C).
The new official QP-bundle release (QP/C/C++ 7.3.0, the matching QM 5.3.0, etc.) is coming out soon (planned for August 1).
--MMS

**Comment by teivah-tech** [comment]
Running latest qm_5.3.0-linux64.zip.
* Tool still says 5.2.5 in About QM.
* Can't open the template files with new project; Also getting ERROR F041.
* Generated code says "This code has been generated by QM 5.2.5".

There seems to be some confusion between version 5.3.0 and 5.2.5 in the latest upload?

**Comment by stefanschober** [comment]
Solved :)
