### ISSUE TITLE
Windows System environment variables

### ISSUE THREAD

**Issue by dzid26** [QuantumLeaps/qm#6]
Few small issues:

1. I unselected Mingw during the installation, since I already have one, but the non-existing path `C:\qp\qtools\mingw32\bin` was still added to Windows PATH. 
2. QPC was not added to envs, and `blinky` couldn't find qpc.h. I am not sure if that was intended. I added QPC system variable and it went further fine. 
3. Next, is probably different issue, but I am stuck here: Is this 32/64bit issue?: 
```/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible C:\qp\qpc/ports/win32-qv/dbg/libqp.a when searching for -lqp
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible C:\qp\qpc/ports/win32-qv/dbg/libqp.a when searching for -lqp
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible C:\qp\qpc/ports/win32-qv/dbg/libqp.a when searching for -lqp
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: cannot find -lqp
/usr/lib/gcc/x86_64-pc-msys/10.2.0/../../../../x86_64-pc-msys/bin/ld: skipping incompatible C:\qp\qpc/ports/win32-qv/dbg/libqp.a when searching for -lqp
collect2: error: ld returned 1 exit status
make: *** [Makefile:216: build/blinky.exe] Error 1```

**Comment by quantum-leaps** [comment]
Ad 1: The QP-bundle installation for Windows will be modified to set the PATH according to the selection of components.

Ad 2: The QPC symbol will NOT be set in the installation. The intent here is exactly to allow users to define this symbol themselves, in case they already have a QPC version that they prefer to use. Please note that QPC is used in the Makefiels only if it is not already defined.

Ad 3: The 32/64bit discrepancy is only an issue, because you have rejected the 32-bit compiler and selected your own 64-bit compiler. If you do this, you own the problem, and now you have to generate a matching 64-bit QPC library. But the main intent of the QP-Win32 port is emulating and testing of the deeply embedded code on Windows. For that, 32-bit compiler is much better suited, because it better matches 32-bit embedded processors. I hope this makes sense.

**Comment by dzid26** [comment]
32bit compiler makes a lot of sense. Thank you for your clarification
